

--last exercise

USE ROLE ACCOUNTDMIN;
USE DATABASE DEMO_DB;
USE WAREHOUSE COMPUTE_WH;
 
CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.SUPPLIER
AS
SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."SUPPLIER";

CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.SUPPLIER_CLONE CLONE SUPPLIER; 

UPDATE SUPPLIER_CLONE SET S_PHONE='###';

SELECT * FROM SUPPLIER_CLONE;

CREATE OR REPLACE TABLE SUPPLIER_CLONE_CLONE
CLONE SUPPLIER_CLONE BEFORE(STATEMENT =>'01b51d70-0001-e495-0005-e22200023756');

SELECT * FROM SUPPLIER_CLONE_CLONE;

DROP TABLE SUPPLIER;

SELECT * FROM SUPPLIER_CLONE_CLONE;
